/**
 * Property-based tests for ops-checklist.js — Properties 16, 17
 *
 * Uses fast-check with minimum 100 iterations per property.
 * Validates: Requirements 8.3, 9.2
 */
import { describe, it, expect, beforeEach } from 'vitest';
import fc from 'fast-check';
import { generateOpsChecklist, renderOpsChecklist } from '../ops-checklist.js';

// ── Generators ──────────────────────────────────────────────

/** Generate a valid changeType. */
const arbChangeType = fc.constantFrom('PanD2C_Flip', '5S_Square');

/** Generate a lane number (positive integer). */
const arbLane = fc.integer({ min: 1, max: 20 });

/** Generate a chute ID string. */
const arbChuteId = fc.stringMatching(/^[A-Z]{0,4}-?\d{3,6}$/);

/** Generate a short description string. */
const arbDescription = fc.stringMatching(/^[A-Za-z0-9 ]{1,40}$/);

/** Generate a ChangeOverviewItem. */
const arbChangeOverviewItem = fc.record({
  chuteId: arbChuteId,
  lane: arbLane,
  changeType: arbChangeType,
  description: arbDescription,
  fromState: fc.option(fc.stringMatching(/^[A-Za-z0-9]{1,10}$/), { nil: undefined }),
  toState: fc.option(fc.stringMatching(/^[A-Za-z0-9]{1,10}$/), { nil: undefined }),
});

/** Generate a non-empty array of ChangeOverviewItems. */
const arbChangeOverviewItems = fc.array(arbChangeOverviewItem, { minLength: 1, maxLength: 15 });

/** Generate an array of ChangeOverviewItems (may be empty). */
const arbChangeOverviewItemsWithEmpty = fc.array(arbChangeOverviewItem, { minLength: 0, maxLength: 15 });

// ── Helpers ─────────────────────────────────────────────────

function makeDom() {
  const el = document.createElement('div');
  el.id = 'panel-ops-checklist';
  return el;
}

// ── Property 16: Incomplete checklist triggers warning ──────

describe('Property 16: Incomplete checklist triggers warning', () => {
  /**
   * **Validates: Requirements 8.3**
   *
   * For any Ops checklist where at least one item has completed === false,
   * the system SHALL produce a warning. All items generated by
   * generateOpsChecklist start with completed: false, so any non-empty
   * input always produces a checklist with incomplete items.
   */
  it('all generated checklist items start with completed: false', () => {
    fc.assert(
      fc.property(arbChangeOverviewItemsWithEmpty, (changeItems) => {
        const checklist = generateOpsChecklist(changeItems);

        // Every item (including AR confirmation) starts incomplete
        for (const item of checklist) {
          expect(item.completed).toBe(false);
        }
      }),
      { numRuns: 100 },
    );
  });

  /**
   * **Validates: Requirements 8.3**
   *
   * For any set of change overview items, rendering the ops checklist
   * SHALL display a warning banner because all items start incomplete.
   */
  it('rendered checklist shows warning banner when items are incomplete', () => {
    fc.assert(
      fc.property(arbChangeOverviewItemsWithEmpty, (changeItems) => {
        const el = makeDom();
        renderOpsChecklist(el, changeItems);

        // generateOpsChecklist always adds at least the AR item (completed: false)
        // so there is always at least one incomplete item → warning must be present
        const banner = el.querySelector('.ops-warning-banner');
        expect(banner).not.toBeNull();
        expect(banner.textContent).toContain('incomplete');
        expect(banner.getAttribute('role')).toBe('alert');
      }),
      { numRuns: 100 },
    );
  });

  /**
   * **Validates: Requirements 8.3**
   *
   * For any non-empty change overview, the checklist has at least
   * changeItems.length + 1 items (changes + AR confirmation), and
   * the warning banner identifies that items are incomplete.
   */
  it('checklist with at least one incomplete item always triggers warning', () => {
    fc.assert(
      fc.property(arbChangeOverviewItems, (changeItems) => {
        const checklist = generateOpsChecklist(changeItems);

        // At least changeItems.length + 1 (AR confirmation)
        expect(checklist.length).toBe(changeItems.length + 1);

        // All start incomplete
        const hasIncomplete = checklist.some((item) => !item.completed);
        expect(hasIncomplete).toBe(true);

        // Render and verify warning
        const el = makeDom();
        renderOpsChecklist(el, changeItems);
        const banner = el.querySelector('.ops-warning-banner');
        expect(banner).not.toBeNull();
      }),
      { numRuns: 100 },
    );
  });
});


// ── Property 17: AR layout confirmation in checklist ────────

describe('Property 17: AR layout confirmation in checklist', () => {
  /**
   * **Validates: Requirements 9.2**
   *
   * The checklist always contains an AR layout confirmation item.
   * There is no go-live button — the checklist is informational only.
   */
  it('no go-live button is rendered', () => {
    fc.assert(
      fc.property(arbChangeOverviewItemsWithEmpty, (changeItems) => {
        const el = makeDom();
        renderOpsChecklist(el, changeItems);

        const goLiveBtn = el.querySelector('.ops-go-live-btn');
        expect(goLiveBtn).toBeNull();
      }),
      { numRuns: 100 },
    );
  });

  /**
   * **Validates: Requirements 9.2**
   *
   * For any set of change items, the AR confirmation checkbox always
   * exists in the rendered checklist and can be toggled.
   */
  it('AR confirmation checkbox exists and is toggleable', () => {
    fc.assert(
      fc.property(arbChangeOverviewItemsWithEmpty, (changeItems) => {
        const el = makeDom();
        renderOpsChecklist(el, changeItems);

        const arCheckbox = el.querySelector('.ops-checkbox[data-id="ar-layout-confirm"]');
        expect(arCheckbox).not.toBeNull();

        // Check the AR checkbox
        arCheckbox.checked = true;
        arCheckbox.dispatchEvent(new Event('change'));

        // No go-live button should exist
        expect(el.querySelector('.ops-go-live-btn')).toBeNull();
      }),
      { numRuns: 100 },
    );
  });

  /**
   * **Validates: Requirements 9.2**
   *
   * The generated checklist always contains exactly one item with
   * isArLayout === true, ensuring the AR confirmation is always present
   * regardless of the change overview input.
   */
  it('checklist always contains exactly one AR layout confirmation item', () => {
    fc.assert(
      fc.property(arbChangeOverviewItemsWithEmpty, (changeItems) => {
        const checklist = generateOpsChecklist(changeItems);

        const arItems = checklist.filter((item) => item.isArLayout === true);
        expect(arItems).toHaveLength(1);
        expect(arItems[0].id).toBe('ar-layout-confirm');
        expect(arItems[0].completed).toBe(false);
      }),
      { numRuns: 100 },
    );
  });
});
